# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  create:
    tags: '*'
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Check if Git tag exists
        run: "export TAG=$(git tag --points-at HEAD | cut -c 2-)"
      - run: npm ci
      - run: npm install web-ext webpack webpack-cli
      - run: npm run build
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: web-ext-artifacts/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
